package verlintas.openvisum.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF4F6BED)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFDDE1FF)
val OnPrimaryContainer = Color(0xFF001453)
val Secondary = Color(0xFF5B5D72)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFE0E1F9)
val OnSecondaryContainer = Color(0xFF181A2C)
val Tertiary = Color(0xFF77536D)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFFFD7F1)
val OnTertiaryContainer = Color(0xFF2D1228)
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF410002)
val Background = Color(0xFFFEFBFF)
val OnBackground = Color(0xFF1B1B1F)
val Surface = Color(0xFFFEFBFF)
val OnSurface = Color(0xFF1B1B1F)
val SurfaceVariant = Color(0xFFE3E1EC)
val OnSurfaceVariant = Color(0xFF46464F)
val Outline = Color(0xFF777680)

val DarkPrimary = Color(0xFFB9C3FF)
val DarkOnPrimary = Color(0xFF192A7A)
val DarkPrimaryContainer = Color(0xFF3543A4)
val DarkOnPrimaryContainer = Color(0xFFDDE1FF)
val DarkSecondary = Color(0xFFC4C5DD)
val DarkOnSecondary = Color(0xFF2D2F42)
val DarkSecondaryContainer = Color(0xFF434559)
val DarkOnSecondaryContainer = Color(0xFFE0E1F9)
val DarkTertiary = Color(0xFFE6BAD7)
val DarkOnTertiary = Color(0xFF44273E)
val DarkTertiaryContainer = Color(0xFF5D3D55)
val DarkOnTertiaryContainer = Color(0xFFFFD7F1)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1B1B1F)
val DarkOnBackground = Color(0xFFE4E1E6)
val DarkSurface = Color(0xFF1B1B1F)
val DarkOnSurface = Color(0xFFE4E1E6)
val DarkSurfaceVariant = Color(0xFF46464F)
val DarkOnSurfaceVariant = Color(0xFFC7C5D0)
val DarkOutline = Color(0xFF91909A)
